[package]
name = "forustm"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = "*"
sapper_std = "*"
#sapper_std = { path="../sapper_std" }
log = "0.3.7"
env_logger = "0.4.2"

serde="1.0.7"
serde_json="1.0.2"
serde_derive="1.0.8"

diesel = { version = "0.13.0", features = ["postgres", "large-tables"] }
diesel_codegen = { version = "0.13.0", features = ["postgres"] }
dotenv = "0.9.0"

chrono = "0.4"
rand = "*"
md5 = "*"

[[bin]]
name = "api_server"
path = "src/api_server.rs"

[[bin]]
name = "webpage_server"
path = "src/webpage_server.rs"

